name: "thug shaker simulator"
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: shake it
        run: |
          python shipit.py
          git add .
          git commit -m ":shipit:"
          git push